//@version=5
indicator("ADX and DI with SMA by FopTun", overlay=true, precision=6)
len = input.int(title="Length", defval=14)
th = input.int(title="threshold", defval=20)
avg = input.int(title="SMA", defval=5)
avg2 = input.int(title="SMA2", defval=10)



TrueRange = math.max(math.max(high-low, math.abs(high-nz(close[1]))), math.abs(low-nz(close[1])))
DirectionalMovementPlus = high-nz(high[1]) > nz(low[1])-low ? math.max(high-nz(high[1]), 0): 0
DirectionalMovementMinus = nz(low[1])-low > high-nz(high[1]) ? math.max(nz(low[1])-low, 0): 0

SmoothedTrueRange = 0.0
SmoothedTrueRange := nz(SmoothedTrueRange[1]) - (nz(SmoothedTrueRange[1])/len) + TrueRange

SmoothedDirectionalMovementPlus = 0.0
SmoothedDirectionalMovementPlus := nz(SmoothedDirectionalMovementPlus[1]) - (nz(SmoothedDirectionalMovementPlus[1])/len) + DirectionalMovementPlus

SmoothedDirectionalMovementMinus = 0.0
SmoothedDirectionalMovementMinus := nz(SmoothedDirectionalMovementMinus[1]) - (nz(SmoothedDirectionalMovementMinus[1])/len) + DirectionalMovementMinus

DIPlus = SmoothedDirectionalMovementPlus / SmoothedTrueRange * 100
DIMinus = SmoothedDirectionalMovementMinus / SmoothedTrueRange * 100

DX = math.abs(DIPlus-DIMinus) / (DIPlus+DIMinus)*100
ADX = ta.sma(DX, len)
SMA = ta.sma(ADX, avg)
SMA2 = ta.sma(ADX, avg2)

Bull = DIPlus > DIMinus
Bear = DIMinus > DIPlus

Green = Bull  // Buy
Red = Bear  // Sell

buycond = Green and Green[1] == 0
sellcond = Red and Red[1] == 0

bullish = ta.barssince(buycond) < ta.barssince(sellcond)
bearish = ta.barssince(sellcond) < ta.barssince(buycond)

buy = bearish[1] and buycond
sell = bullish[1] and sellcond

plotshape(true ? buy : na,
 style=shape.circle,
 title='Buy Signal',
 location=location.bottom,
 color=color.new(#4caf50, 0))

plotshape(true ? sell : na,
 style=shape.circle,
 title='Sell Signal',
 location=location.bottom,
 color=color.new(#f23645, 0))

plot(DIPlus, color=color.new(color.green, 0), title="DI+")
plot(DIMinus, color=color.new(color.orange, 0), title="DI-")
plot(ADX, color=color.new(#3bf2ff, 0), title="ADX")
plot(SMA, color=color.new(color.red, 0), title="SMA")
plot(SMA2, color=color.new(color.blue, 0), title="SMA2")
// hline(th, color=color.blak, linestyle=dashed)
